version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t <your-repository>:<your-tag> .
      - docker tag admin:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/admin:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/admin:latest

      # Uncomment the following lines if you want to deploy to EKS using kubectl
      # - echo "Configuring kubectl..."
      # - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name reffy-k8s
  

